name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      # ポータルサイトをビルド
      - name: Build portal site
        run: npx gulp build

      # shops サイトがある場合もビルド
      - name: Build shops site
        run: |
          if [ -d "shops/src" ]; then
            npx gulp build --site shops || echo "No shops site to build"
          fi

      # デプロイ (dist/ をルート、shops/dist/ を /shops/ に配置)
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: .  # ルートに dist/ と shops/ の中身を配置
          force_orphan: true
